# v2 syntax
version: '2'

# Named volumes
volumes:
  test-mysql-data:
    driver: local
  sandbox-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    volumes:
      - test-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.4-nginx
    container_name: test-app
    volumes:
      - ./application:/var/www/app
    environment:
      VIRTUAL_HOST: accordous-test.provider.net.br
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: accordous-test.provider.net.br
      LETSENCRYPT_EMAIL: jpaulolxm@gmail.com
    ports:
      - "80:8080"
      - "3000:3000"
    links:
      - mysql

  # Redis
  cache:
    image: redis:4.0
    container_name: sandbox-redis
    command: --appendonly yes
    volumes:
      - sandbox-redis-data:/data
    ports:
      - "6379:6379"
  # Laravel Queues
  queue:
    image: ambientum/php:7.4
    container_name: sandbox-queue
    command: php artisan queue:listen
    volumes:
      - ./application:/var/www/app
    links:
      - mysql
      - cache
